# Generated by Django 5.0.dev20230914191712 on 2023-09-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('data_reserva', models.DateField(blank=True, null=True)),
                ('locatario', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
